export const tenseSelectionInit = [
   { id: 0, value: 'all', isChecked: true },
   { id: 1, value: 'present', isChecked: false },
   { id: 2, value: 'past', isChecked: false },
   { id: 3, value: 'present continuous', isChecked: false },
   { id: 4, value: 'past continuous', isChecked: false },
   { id: 5, value: 'present perfect', isChecked: false },
   { id: 6, value: 'past perfect', isChecked: false },
   { id: 7, value: 'future perfect', isChecked: false },
   { id: 8, value: 'imperfect', isChecked: false },
   { id: 9, value: 'imperative', isChecked: false },
];

export const verbSelectionInit = [
   { id: 0, value: 'all', isChecked: true },
   { id: 1, value: 'amar (-AR)', isChecked: false },
   { id: 2, value: 'beber (-ER)', isChecked: false },
   { id: 3, value: 'decidir (-IR)', isChecked: false },
   { id: 4, value: 'vir', isChecked: false },
   { id: 5, value: 'dizer', isChecked: false },
   { id: 6, value: 'ler', isChecked: false },
   { id: 7, value: 'dar', isChecked: false },
   { id: 8, value: 'estar', isChecked: false },
   { id: 9, value: 'fazer', isChecked: false },
   { id: 10, value: 'ir', isChecked: false },
   { id: 11, value: 'ouvir', isChecked: false },
   { id: 12, value: 'poder', isChecked: false },
   { id: 13, value: 'querer', isChecked: false },
   { id: 14, value: 'saber', isChecked: false },
   { id: 15, value: 'ser', isChecked: false },
   { id: 16, value: 'ter', isChecked: false },
   { id: 17, value: 'trazer', isChecked: false },
   { id: 18, value: 'ver', isChecked: false },
   { id: 19, value: 'pôr', isChecked: false },
];
